CREATE TABLE IF NOT EXISTS public.groups
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    levelnum integer NOT NULL,
    ordernum integer NOT NULL,
    parentnode integer,
    rootnode integer,
    txtgroup character varying(150) COLLATE pg_catalog."default",
    CONSTRAINT groups_pkey PRIMARY KEY (id),
    CONSTRAINT unique_rootnode_ordernum UNIQUE (rootnode, ordernum),
    CONSTRAINT unique_parentnode_txtgroup UNIQUE (parentnode, txtgroup)
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.groups
    OWNER to postgres;

CREATE INDEX IF NOT EXISTS index_for_txtgroup
    ON public.groups USING btree
    (txtgroup COLLATE pg_catalog."default" ASC NULLS LAST)
    TABLESPACE pg_default;
